### ISSUE TITLE
Case-sensitive paths issue when building under Linux

### ISSUE THREAD

**Issue by jip** [ellisonch/CFGLib#2]
The problem:
```
> msbuild
[...]
  Processing resource file "Properties/Resources.resx" into "obj/Debug/Grammars.Properties.Resources.resources".
/home/user/CFGLib/Grammars/Properties/Resources.resx(129,5): error MSB3103: Invalid Resx file. Could not find a part of the path "/home/user/CFGLib/Grammars/annotated/arithmetic.ebnf". Line 129, position 5.
```
How to fix:
in the file
> CFGLib/Grammars/Properties/Resources.resx

replace strings:
> <value>..\annotated\arithmetic.ebnf
> <value>..\raw\arithmetic.ebnf
> <value>..\raw\ebnf_actual.ebnf
> <value>..\raw\ebnf_bench.ebnf

by
> <value>..\Annotated\Arithmetic.ebnf
> <value>..\Raw\Arithmetic.ebnf
> <value>..\Raw\Ebnf_actual.ebnf
> <value>..\Raw\Ebnf_bench.ebnf

respectively.

**Comment by ellisonch** [comment]
Hey @jip thanks for the bug report!  I believe I have it fixed.  Let me know if I missed something!
